### ISSUE TITLE
File name too long (os error 36)

### ISSUE THREAD

**Issue by chrusart** [getsentry/sentry-cli#142]
package.json:
```javascript
{
  "name": "testmin",
  "version": "0.0.1",
  "private": true,
  "dependencies": {
    "react-native-sentry": "^0.30.0"
  }
}
```
or just command below fails with this error.

This runs on circleci server with docker image ```circleci/android:api-23-alpha```.
```
node -v v8.9.0
npm -v 5.5.1
```

When I run this docker image locally on my mac and do the same commands, it's ok.

cicleci:
```Linux a4ad0ec75f00 4.4.0-97-generic #120~14.04.1-Ubuntu SMP Wed Sep 20 15:53:13 UTC 2017 x86_64 GNU/Linux```

I know package.json is a react native but command to install sentry-cli-binary independently fails, react native package just fetches sentry-cli-Linux-x86_64 and tries to install it.

```
circleci@a4ad0ec75f00:~/testmin$ npm install sentry-cli-binary

> sentry-cli-binary@1.22.0 install /home/circleci/testmin/node_modules/sentry-cli-binary
> node ./bin/install-sentry-cli

fetching sentry-cli-Linux-x86_64 ████████████████████ 100% 0.0s
error: File name too long (os error 36)
Something went wrong!

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sentry-cli-binary@1.22.0 install: `node ./bin/install-sentry-cli`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sentry-cli-binary@1.22.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2017-11-07T16_01_53_581Z-debug.log
circleci@a4ad0ec75f00:~/testmin$
```
/home/circleci/.npm/_logs/2017-11-07T16_01_53_581Z-debug.log:
```
592 verbose linkBins sentry-cli-binary@1.22.0
593 verbose linkBins [ { 'sentry-cli': 'bin/sentry-cli' },
593 verbose linkBins   '/home/circleci/testmin/node_modules/.bin',
593 verbose linkBins   false ]
594 verbose linkMans sentry-cli-binary@1.22.0
595 silly doSerial global-link 128
596 silly doParallel update-linked 128
597 silly doSerial install 128
598 silly install progress@2.0.0
599 info lifecycle progress@2.0.0~install: progress@2.0.0
600 silly install sentry-cli-binary@1.22.0
601 info lifecycle sentry-cli-binary@1.22.0~install: sentry-cli-binary@1.22.0
602 verbose lifecycle sentry-cli-binary@1.22.0~install: unsafe-perm in lifecycle true
603 verbose lifecycle sentry-cli-binary@1.22.0~install: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/circleci/testmin/node_mo$
604 verbose lifecycle sentry-cli-binary@1.22.0~install: CWD: /home/circleci/testmin/node_modules/sentry-cli-binary
605 silly lifecycle sentry-cli-binary@1.22.0~install: Args: [ '-c', 'node ./bin/install-sentry-cli' ]
606 silly lifecycle sentry-cli-binary@1.22.0~install: Returned: code: 1  signal: null
607 info lifecycle sentry-cli-binary@1.22.0~install: Failed to exec install script
608 verbose unlock done using /home/circleci/.npm/_locks/staging-47d78ebebf382cdc.lock for /home/circleci/testmin/node_modules/.staging
609 verbose stack Error: sentry-cli-binary@1.22.0 install: `node ./bin/install-sentry-cli`
609 verbose stack Exit status 1
609 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
609 verbose stack     at emitTwo (events.js:126:13)
609 verbose stack     at EventEmitter.emit (events.js:214:7)
609 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
609 verbose stack     at emitTwo (events.js:126:13)
609 verbose stack     at ChildProcess.emit (events.js:214:7)
609 verbose stack     at maybeClose (internal/child_process.js:925:16)
609 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
610 verbose pkgid sentry-cli-binary@1.22.0
611 verbose cwd /home/circleci/testmin
612 verbose Linux 4.4.0-97-generic
613 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "sentry-cli-binary"
```

Works on VirtualBox Ubuntu 16.4.03 as well.

Thank you for any help.

**Comment by chrusart** [comment]
Damn, the same on CircleCI Mac builds:
```
Darwin static.162.252.208.11.cyberlynk.net 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```

```
fetching sentry-cli-Darwin-x86_64 100%
error: File name too long (os error 63)
Something went wrong!
```
* os error different than linux one

My mac uname:
```
Darwin chrusart 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```

On mac kernels are the same.

**Comment by mitsuhiko** [comment]
I have absolutely no idea what could cause this. My guess is that a shebang is wrong or for some reason huge paths are passed somewhere. I already looked into all places where this could be and the paths you provided don't seem very long. What we attempt to do is invoke `__dirname + '/../sentry-cli`. Can you share which working directory you are in? Path working directory is too deeply nested? Mac path length is often around 255 characters or less for binaries (i think 120 on linux).

**Comment by chrusart** [comment]
Hi, 

paths looks ok:
```__dirname + '/../sentry-cli```
```/Users/distiller/test/node_modules/sentry-cli-binary/bin/../sentry-cli```
(from install-sentry-cli script)
error is when this binary is invoked:
```
bash-3.2$ pwd
/Users/distiller/test/node_modules/sentry-cli-binary
bash-3.2$ ./sentry-cli --help
error: File name too long (os error 63)
```
I can't even call --help on this binary, on my mac, virtualbox, the same docker image it's fine.

**Comment by chrusart** [comment]
I downloaded directly from github:
curl -L https://github.com/getsentry/sentry-cli/releases/download/1.22.0/sentry-cli-Darwin-x86_64 -o sentry-cli_
hash is the same,
output the same
bash-3.2$ ./sentry-cli_ --help
error: File name too long (os error 63)

**Comment by chrusart** [comment]
Ok,

it came out that running with sudo resolves the problem
```
bash-3.2$ ./sentry-cli --version
error: File name too long (os error 63)
```
```
bash-3.2$ sudo ./sentry-cli --version
sentry-cli 1.22.0
```
Some CircleCI machines permissions,
and not accurate error output.

**Comment by jan-auer** [comment]
I just [tried this out](https://circleci.com/gh/jan-auer/circle-test/9) and it is **not** an issue with sentry-cli itself.

**Comment by marcomorain** [comment]
I’ll take a look into this from the CircleCI end on Monday.

**Comment by chrusart** [comment]
Hi @jan-auer ,
thanks for your test and time.

I've tested exactly your config (copy-paste), it fails for us! o_o
Im getting paranoid, I've removed even checkout step, fails (of course).

So, my CircleCI project settings (don't know what else I can give):
Build macOS project: No
OS to use for builds: Ubuntu 14.04 (Trusty)
GitHub Status updates: On
Build forked pull requests: Off
Pass secrets to builds from forked pull requests: Off
Only build pull requests: Off
Auto-cancel redundant builds (Does not apply to workflows): Off
nothing else set in other configuration.

I've tested your configuration on MacOS build:
```
version: 2
jobs:
  build:
    macos:
      xcode: '9.0'
    steps:
      - checkout
      - run:
          name: Install sentry-cli
          command: npm install sentry-cli-binary
      - run:
          name: Print sentry-cli version
          command: node_modules/.bin/sentry-cli --version
```
```
#!/bin/bash -eo pipefail
npm install sentry-cli-binary
^D^D
> sentry-cli-binary@1.22.0 install /Users/distiller/project/node_modules/sentry-cli-binary
> node ./bin/install-sentry-cli

fetching sentry-cli-Darwin-x86_64  0% 5.2sfetching sentry-cli-Darwin-x86_64  1% 6.8sfetching sentry-cli-Darwin-x86_64  1% 5.1sfetching sentry-cli-Darwin-x86_64  2% 4.5sfetching sentry-cli-Darwin-x86_64  3% 3.3sfetching sentry-cli-Darwin-x86_64  5% 2.6sfetching sentry-cli-Darwin-x86_64  7% 1.9sfetching sentry-cli-Darwin-x86_64  10% 1.5sfetching sentry-cli-Darwin-x86_64  13% 1.2sfetching sentry-cli-Darwin-x86_64  17% 1.1sfetching sentry-cli-Darwin-x86_64  20% 0.9sfetching sentry-cli-Darwin-x86_64  24% 0.8sfetching sentry-cli-Darwin-x86_64  29% 0.7sfetching sentry-cli-Darwin-x86_64  34% 0.6sfetching sentry-cli-Darwin-x86_64  39% 0.5sfetching sentry-cli-Darwin-x86_64  46% 0.4sfetching sentry-cli-Darwin-x86_64  53% 0.3sfetching sentry-cli-Darwin-x86_64  60% 0.3sfetching sentry-cli-Darwin-x86_64  66% 0.2sfetching sentry-cli-Darwin-x86_64  72% 0.2sfetching sentry-cli-Darwin-x86_64  82% 0.1sfetching sentry-cli-Darwin-x86_64  93% 0.0sfetching sentry-cli-Darwin-x86_64  100% 0.0s
error: File name too long (os error 63)
Something went wrong!

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sentry-cli-binary@1.22.0 install: `node ./bin/install-sentry-cli`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sentry-cli-binary@1.22.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/distiller/.npm/_logs/2017-11-13T09_35_38_228Z-debug.log
Exited with code 1
```

I think it should go back to CircleCI.

**Comment by mitsuhiko** [comment]
@chrusart Can you confirm this also still happens for you on linux?

**Comment by chrusart** [comment]
Doing on Mac:
```
version: 2
jobs:
  build:
    macos:
      xcode: '9.0'
    steps:
      - checkout
      - run:
          name: Install sentry-cli
          command: sudo npm install sentry-cli-binary
      - run:
          name: Print sentry-cli version
          command: node_modules/.bin/sentry-cli --version
```
```sudo npm install sentry-cli-binary``` succeeds but:
```
node_modules/.bin/sentry-cli --version
```
```
#!/bin/bash -eo pipefail
node_modules/.bin/sentry-cli --version
^D^Derror: File name too long (os error 63)
Exited with code 1
```

On Linux (w/ and w/o ```- checkout``` ;)):
```
version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-23-alpha
    steps:
      - checkout
      - run:
          name: Install node js
          command: curl --silent --location https://deb.nodesource.com/setup_8.x | sudo bash - && sudo apt-get install -y nodejs
      - run:
          name: Install sentry-cli
          command: sudo npm install sentry-cli-binary
      - run:
          name: Print sentry-cli version
          command: node_modules/.bin/sentry-cli --version
```
```
#!/bin/bash -eo pipefail
sudo npm install sentry-cli-binary

> sentry-cli-binary@1.22.0 install /home/circleci/project/node_modules/sentry-cli-binary
> node ./bin/install-sentry-cli

{ Error: EACCES: permission denied, open '/home/circleci/project/node_modules/sentry-cli-binary/bin/../sentry-cli'
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/home/circleci/project/node_modules/sentry-cli-binary/bin/../sentry-cli' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sentry-cli-binary@1.22.0 install: `node ./bin/install-sentry-cli`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sentry-cli-binary@1.22.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-13T09_57_36_703Z-debug.log
Exited with code 1
```

or with yarn (Linux):
```
version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-23-alpha
    steps:
      - run:
          name: Install node js
          command: curl --silent --location https://deb.nodesource.com/setup_8.x | sudo bash - && sudo apt-get install -y nodejs
      - run:
          name: Install sentry-cli
          command: |
              curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
              echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

              sudo apt-get update
              sudo apt-get install yarn
              yarn -v

              sudo yarn add sentry-cli-binary
      - run:
          name: Print sentry-cli version
          command: node_modules/.bin/sentry-cli --version
```
```
#!/bin/bash -eo pipefail
node_modules/.bin/sentry-cli --version
error: File name too long (os error 36)
Exited with code 1
```

Hope this also helps.

**Comment by chrusart** [comment]
Yes, on Linux:
```
version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-23-alpha
    steps:
      - checkout
      - run:
          name: Install node js
          command: curl --silent --location https://deb.nodesource.com/setup_8.x | sudo bash - && sudo apt-get install -y nodejs
      - run:
          name: Install sentry-cli
          command: npm install sentry-cli-binary
      - run:
          name: Print sentry-cli version
          command: node_modules/.bin/sentry-cli --version
```
```
#!/bin/bash -eo pipefail
npm install sentry-cli-binary

> sentry-cli-binary@1.22.0 install /home/circleci/project/node_modules/sentry-cli-binary
> node ./bin/install-sentry-cli

fetching sentry-cli-Linux-x86_64  4% 0.4sfetching sentry-cli-Linux-x86_64  10% 0.3sfetching sentry-cli-Linux-x86_64  15% 0.3sfetching sentry-cli-Linux-x86_64  21% 0.2sfetching sentry-cli-Linux-x86_64  28% 0.2sfetching sentry-cli-Linux-x86_64  36% 0.2sfetching sentry-cli-Linux-x86_64  41% 0.2sfetching sentry-cli-Linux-x86_64  49% 0.1sfetching sentry-cli-Linux-x86_64  56% 0.1sfetching sentry-cli-Linux-x86_64  63% 0.1sfetching sentry-cli-Linux-x86_64  71% 0.1sfetching sentry-cli-Linux-x86_64  78% 0.1sfetching sentry-cli-Linux-x86_64  86% 0.0sfetching sentry-cli-Linux-x86_64  92% 0.0sfetching sentry-cli-Linux-x86_64  100% 0.0s
error: File name too long (os error 36)
Something went wrong!

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sentry-cli-binary@1.22.0 install: `node ./bin/install-sentry-cli`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sentry-cli-binary@1.22.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2017-11-13T09_17_01_462Z-debug.log
Exited with code 1
```

**Comment by marcomorain** [comment]
This is odd, when I run an SSH build I can install the sentry cli module and run it without issue (on CircleCI 2.0 `macos: xcode: "9.0"`).

We have 2 reports of this issue - this issue and a second user has submitted a support ticket to the CircleCI Zendesk.

**Comment by jan-auer** [comment]
@chrusart On a side note: Never install with `sudo npm install sentry-cli-binary`. This is a known issue tracked in #123.

**Comment by chrusart** [comment]
Without checkout:
(empty package.json is needed)
```
version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-23-alpha
    environment:
      PACKAGE_JSON: '{ "name": "test", "version": "0.0.1" }'
    steps:
      - run:
          name: Install node js
          command: curl --silent --location https://deb.nodesource.com/setup_8.x | sudo bash - && sudo apt-get install -y nodejs
      - run:
          name: Dumb package.json
          command: echo $PACKAGE_JSON >> ./package.json
      - run:
          name: Install sentry-cli
          command: npm install sentry-cli-binary
      - run:
          name: Print sentry-cli version
          command: node_modules/.bin/sentry-cli --version
```
```
#!/bin/bash -eo pipefail
npm install sentry-cli-binary

> sentry-cli-binary@1.22.0 install /home/circleci/project/node_modules/sentry-cli-binary
> node ./bin/install-sentry-cli

fetching sentry-cli-Linux-x86_64  5% 0.3sfetching sentry-cli-Linux-x86_64  11% 0.3sfetching sentry-cli-Linux-x86_64  18% 0.2sfetching sentry-cli-Linux-x86_64  25% 0.2sfetching sentry-cli-Linux-x86_64  31% 0.2sfetching sentry-cli-Linux-x86_64  37% 0.2sfetching sentry-cli-Linux-x86_64  45% 0.1sfetching sentry-cli-Linux-x86_64  53% 0.1sfetching sentry-cli-Linux-x86_64  59% 0.1sfetching sentry-cli-Linux-x86_64  67% 0.1sfetching sentry-cli-Linux-x86_64  73% 0.1sfetching sentry-cli-Linux-x86_64  81% 0.0sfetching sentry-cli-Linux-x86_64  90% 0.0sfetching sentry-cli-Linux-x86_64  100% 0.0s
error: File name too long (os error 36)
Something went wrong!

npm WARN test@0.0.1 No description
npm WARN test@0.0.1 No repository field.
npm WARN test@0.0.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sentry-cli-binary@1.22.0 install: `node ./bin/install-sentry-cli`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sentry-cli-binary@1.22.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2017-11-13T10_29_46_424Z-debug.log
Exited with code 1
```
