### ISSUE TITLE
failed to install in a Yarn 3.x mono repo 

### ISSUE THREAD

**Issue by lightchaser411** [getsentry/sentry-cli#1477]
### Environment

sentry/cli 1.74.6
node 19.6.0
yarn 3.3.1
.yarnrc
```
logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard
  - code: YN0076
    level: discard
  - code: YN0013
    level: discard

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: "@yarnpkg/plugin-stage"
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
```

### Steps to Reproduce

1. Install sentry with above cli

### Expected Result

Sentry finds node

### Actual Result

```
# This file contains the result of Yarn building a package (@sentry/cli@npm:1.74.6)
# Script name: install

command not found: node
```
