### ISSUE TITLE
Homebrew Formula doesn't detect GitHub Actions Linux runners

### ISSUE THREAD

**Issue by mrackwitz** [getsentry/sentry-cli#1711]
### Environment

ubuntu-latest on GitHub Actions.

### Steps to Reproduce

Install sentry-cli via [Homebrew on Linux](https://docs.brew.sh/Homebrew-on-Linux), e.g.
```yaml
jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - name: Install Sentry
      run: |
        # Enable Linuxbrew (according to GitHub Actions docs)
        # Note: changes the PATH, so must happen in the same shell
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install getsentry/tools/sentry-cli
```

While this might be a very unusual choice for a package manager, it makes a little more sense in a mixed macOS / Linux setup.

### Expected/Actual Result

Installation fails with:
```
Unsupported architecture
```

The problem here seems to be detecting the architecture [in the formula](https://github.com/getsentry/homebrew-tools/blob/master/Formula/sentry-cli.rb). Afaict the `x86_64` binaries should do the trick here?
