### ISSUE TITLE
"A project slug is required" for upload-sourcemaps in GitLab CI

### ISSUE THREAD

**Issue by axnsan12** [getsentry/sentry-cli#451]
```console
$ sentry-cli releases files $VERSION upload-sourcemaps --rewrite ./dist/ --url-prefix /usr/src/app/
Analyzing 4 sources
Rewriting sources
Adding source map references
error: A project slug is required

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
```

This seems related to #95. The release was previously created using ``sentry-cli``.

```console
$ sentry-cli releases new -p $PROJECT $VERSION
Created release c4ea65d6fd63f468eb69ac3a9d996c1f9521c764.
$ sentry-cli releases set-commits --auto $VERSION
+---------------+--------------+
| Repository    | Revision     |
+---------------+--------------+
| < REPO NAME > | c4ea65d6fd63 |
+---------------+--------------+
```

**Comment by hamadmj** [comment]
Can confirm the same issue. Is there a workaround to this?

**Comment by axnsan12** [comment]
The command doesn't seem to accept a project slug argument, but you can export the ``SENTRY_PROJECT`` envelope variable and it will be picked up.

**Comment by Yankovsky** [comment]
Can you add --project option to `sentry-cli releases files upload-sourcemaps`?
Or tell me where should it be.
It is very strange that SENTRY_PROJECT env variable should be declared and there is no option to specify project in command.

**Comment by EddyP23** [comment]
Same here. Very weird on two fronts. It's been 8 months and no fix came out for a reasonably simple bug. And also docs don't mention this. Sad.

**Comment by MrGWest** [comment]
So the problem is not due to having more than on project released? My CircleCI config has the following line `sentry-cli releases new -p node-server -p web-client $CIRCLE_SHA1`.

**Comment by Meeeeow** [comment]
Same error message here, a `SENTRY_PROJECT` environment variable was dynamic exported at same stage, tested work with echo, but sentry cli says "project slug is required".

Temporary solution is write everything include token and project name in a `.sentryclirc` and delete it after source map uploaded

**Comment by rtyshyk** [comment]
@Meeeeow 
Works fine for me with env variables.
```yml
  variables:
    SENTRY_URL: https://selfhosted/
    SENTRY_ORG: org
    SENTRY_AUTH_TOKEN: SECRET
    SENTRY_PROJECT: projectname
  script:
    - cd app
    - npm install --loglevel warn
    - npm run build
    - mv dist/config.js.example dist/config.js
    - HASH=`git log --pretty="%h" -n1 HEAD`
    - VERSION=$CI_COMMIT_REF_NAME.$HASH
    - sed -i -e "s,%APP_VERSION%,$VERSION,g" dist/config.js
    # create release in sentry
    - sentry-cli releases new -p $SENTRY_PROJECT $VERSION
    - sentry-cli releases set-commits --auto $VERSION
    - sentry-cli releases files $VERSION upload-sourcemaps dist
```
