### ISSUE TITLE
sentry release failed on GitHub workflow

### ISSUE THREAD

**Issue by MahaZaid** [getsentry/sentry-cli#945]
### Environment

Which SDK and version?
.dotnet core 3

### Steps to Reproduce
I am trying to publish a release through GitHub workflow

```
- uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ env.SENTRY_PROJECT }}
      with:
        environment: ${{ env.EKS_CLUSTER_NAME }}
        version: ${{ env.VERSION }}
```
### Expected Result

publish the release

### Actual Result

<img width="1075" alt="Screen Shot 2021-04-14 at 2 27 37 PM" src="https://user-images.githubusercontent.com/20710308/114710038-91321600-9d2d-11eb-86b9-4e20089a03e9.png">

I am already adding fetch before running the plugin

Is there a way to publish the release without the GitHub plugin ?
